### ISSUE TITLE
X displaying too large

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/workstream-website#10]
Additionally, X is way too big and displaying weirdly (white outline that shouldn't be ther). I think this has something to do with svgs exported from Sketch, so Monday I will send oyu a better one. However the issue remains that somehow it is way too big

**Comment by oliverjam** [comment]
Yeah I think this SVG is weird. Maybe try exporting from Illustrator?

I just chucked that in, so will finesse the sizing now.

**Comment by Jamchiller** [comment]
Cool

**Comment by oliverjam** [comment]
Is the size okay now? I know it's still the old crappier SVG

**Comment by lickcreative** [comment]
It's perfect. I just realised I can't close issue's that I opened. Annoying

**Comment by oliverjam** [comment]
That's really weird. Maybe cause you're on Lick's account?
