### ISSUE TITLE
About/Contact Buttons not working

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/workstream-website#11]
Buttons need to direct to section

**Comment by oliverjam** [comment]
They do on my machine :/ Or do you mean implement the smooth-scrolling with JS? Right now they just jump to the section

**Comment by Jamchiller** [comment]
Mine don't even look like buttons, nothing happens on hover or click. And yeah should be smooth scrolling

**Comment by oliverjam** [comment]
They aren't meant to look like buttons are they? They're links in the mockup you sent. Only 'Sign In' is a button.

They change to gold when I hover and jump to the right section when I click.

**Comment by Jamchiller** [comment]
Here's an example. I mean that the cursor doesn't change on hover like it would on a hyperlink or button. Also example of the flashing
![mar-18-2017 13-37-17](https://cloud.githubusercontent.com/assets/16238581/24072518/0fdc251a-0be0-11e7-89c4-51d3c761c233.gif)

**Comment by oliverjam** [comment]
Oh shit that's so weird. I didn't notice cause my window is so much bigger, but somehow when the page gets smaller the X overlaps the head invisibly and blocks you from clicking the links lol.

Easy fix though, thanks for finding

**Comment by oliverjam** [comment]
Should be fixed?

If it is close the issue pls

**Comment by lickcreative** [comment]
Would you be able to add a js sliding motion when you click on the buttons? So it's smooth and the user knows that they're on the same page rather than moved to a completely different one

**Comment by oliverjam** [comment]
Yeah that's on the list #21
