### ISSUE TITLE
Login/Send buttons lack gradient and look/feel of my buttons

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/workstream-website#12]
Let me know if you need me to send you better svgs or something

**Comment by oliverjam** [comment]
Yeah I just hadn't got round to doing the gradient yet. Just chucked the colours in when I mocked up the page

**Comment by Jamchiller** [comment]
Cool

**Comment by oliverjam** [comment]
@Jazzalenko how do they look?

**Comment by lickcreative** [comment]
Looking nice! Could you make the text in the buttons just slightly smaller and perhaps move the 'log in' text ever so slightly down (if you can). I think it's probably centred but the weight of the word makes it feel closer to the top than the bottom. 

Also, would you be able to move the Log in button just across to the left a bit, feels slightly too close to the rhs of the window. Pedantic I know but

**Comment by oliverjam** [comment]
How's that?

**Comment by lickcreative** [comment]
Would you be able to increase the padding on the navbar at the top to 1.5em? Think it looks better when slightly farther from the top. Just tried it by tweaking the css and looks alright

**Comment by oliverjam** [comment]
Done

**Comment by lickcreative** [comment]
Sexy af
