### ISSUE TITLE
Text too large

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/workstream-website#13]
Feel that text is too large in general across the site. Needs to be taken down a couple of points to match prototypes

**Comment by oliverjam** [comment]
yeah I bumped it up the other day because there was crazy whitespace and all the lines of text ended up too long. It might be because my screen is bigger and higher res, but the page looks really empty with smaller text.

![screen shot 2017-03-18 at 13 22 12](https://cloud.githubusercontent.com/assets/9408641/24072340/f82d9824-0bdd-11e7-812e-f0d6b166e4c1.png)

**Comment by Jamchiller** [comment]
I'll play around with this but this is more of a problem with the wideness of that window than anything else. It needs to work at sizes. In my mind the length of that iphone is making the page weird, maybe makeit smaller like my designs?

**Comment by oliverjam** [comment]
It's just my 15" Macbook, not that wide :P

Do you want me to constrain the page width so it doesn't get super wide? I'll reduce the size of the iPhone, but that won't help with the horizontal space.

**Comment by Jamchiller** [comment]
Dude none of these are criticisms, they're things that need to be fixed. When I said that it was wide, I mean that I did not design my mockup at the full screen width of your 15" macbook. So I need to. But as I said, we need to make this work at all sizes, so I will mock it up. You know as well as I do that it's hard to makeit work for all sizes but also very necessary

**Comment by oliverjam** [comment]
Yeah I know, it's cool. I was suggesting a solution — it's quite normal to have a max-width on a page so you don't end up with everything super stretched out on wider screens. Like this:
![screen shot 2017-03-18 at 13 45 30](https://cloud.githubusercontent.com/assets/9408641/24072580/308ca3c4-0be1-11e7-80e5-8b6ccdf12f7d.png)

**Comment by Jamchiller** [comment]
Just discovered the emoji thing. Cool. Yep. Max width would be brilliant

**Comment by oliverjam** [comment]
How's that?

**Comment by oliverjam** [comment]
@Jazzalenko Happy with the font-size and max-width?
