### ISSUE TITLE
Macbook should be iMac? 

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/workstream-website#14]
I feel that the Macbooks should be iMacs as these tend to be used more for product shots . This is low priority.

**Comment by oliverjam** [comment]
Yeah it was late and making a CSS-only iMac stand was really hard so I just added a rectangle in to make it a laptop lol.

Aren't most Workstream users on laptops rather than iMacs?

**Comment by Jamchiller** [comment]
Well, most will be on in-store computers. Then head office people will be on laptops/monitors. But as I mentioned it just felt better for product shots. Happy to leave it as iMac for now.

**Comment by oliverjam** [comment]
Leave as iMac or Macbook?

I can do a more stylised iMac quite quickly, without the curvy realistic looking stand. Anything that isn't a rectangle will take more time though

**Comment by Jamchiller** [comment]
Leave it for a bit. Not as important. Will review tomorrow, put this issue on hold

**Comment by oliverjam** [comment]
We've decided to use bare videos without a device wrapper now, so I'm closing this.
