### ISSUE TITLE
Cross-browser testing

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/workstream-website#16]

**Comment by oliverjam** [comment]
It's super broken in IE 🤣

**Comment by lickcreative** [comment]
Lol. In safari it looks alright but the bg css boxes are very white for some reason. Works alright in firefox. Really starting to feel like we'll have to remove the css boxes

**Comment by oliverjam** [comment]
Yeah the gradients are fucking stuff up I think. Even on my Chrome the gradients get banding/dithering lines as they rotate. I'll try flat colours to see if that helps

**Comment by oliverjam** [comment]
Does that look any better?

**Comment by lickcreative** [comment]
Yep. Fixed. Still getting flicking #8 problem in Chrome though. Getting there!
