### ISSUE TITLE
Arrow movement

### ISSUE THREAD

**Issue by lickcreative** [oliverjam/workstream-website#20]
Could you please make the arrow the points downwards start moving from the start, rather than waiting 5 seconds? Just so we have some movement on the home page from first visit (especiallys ince we may be getting rid of the css boxes)

**Comment by oliverjam** [comment]
Yeah it was just delayed so that it didn't distract you as you read the text. I was worried the bouncey thing would grab your attention before you read anything, but I guess the animation is less attention-grabby now

**Comment by oliverjam** [comment]
Better?
