### ISSUE TITLE
Add 4 videos into section

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/workstream-website#25]
Four videos have been saved in the assets folder. Hope they're alright. Might need transcoding to mp4?

Let me know - remember this was the most recent mockup: 
![desktop draft 4](https://cloud.githubusercontent.com/assets/16238581/24212755/4634525e-0f28-11e7-8aab-00da842ef705.png)

**Comment by oliverjam** [comment]
Done. We need to consider some UX here — do the videos autoplay or only play when you click them? Should the first one that's fully opaque be playing automatically?

Also what order do they go in?

**Comment by Jamchiller** [comment]
Hey I completely forgot to reply. I think that if possible they should all autoplay. For the fact that this might make them look more clickable and also because they aren't the nicest videos (kinda slow), so playing them all will distract from each one. Plus, they're not really meant to be focussed on too much. 

In terms of order: Dashboard - Asset Library (to the right of dashboard) - Auto Artworking - Store Ordering.

Thanks

**Comment by oliverjam** [comment]
Yeah all autoplaying is easier anyway — don't have to write any JS to make them play on click. I'll sort that today

**Comment by oliverjam** [comment]
Wow I already had them in the right order. Good guess.

@Jazzalenko What about the copy for this section? I've only got one title/paragraph now (for Dashboard). Can you give me the other three?

**Comment by Jamchiller** [comment]
Nice. Looks great. Sanj is going over the text now and getting some nice stuff. Maybe implement the CMS and putting in this text will be a good tester? The length you've got on the test ones is about right.

**Comment by oliverjam** [comment]
I would say the CMS is something that should be prioritised after stuff that actually affects the site going live. It'll take a bit of time, so it'd be worth putting the text into the HTML manually at first just to go live, and implementing the CSS later so the site can be updated as needed.

**Comment by Jamchiller** [comment]
Cool cool didn't realise it would go in that order. I'll try wrangle the text off sanj today

**Comment by oliverjam** [comment]
@Jazzalenko This copy is in now, happy to close?

**Comment by Jamchiller** [comment]
Yep!
