### ISSUE TITLE
Add correct video to iPhone

### ISSUE THREAD

**Issue by oliverjam** [oliverjam/workstream-website#26]

**Comment by Jamchiller** [comment]
When the video resets, it seems to show some sort of video controls. Is that a problem with my video or the code?

**Comment by oliverjam** [comment]
I'm not seeing any controls. Screenshot?

**Comment by Jamchiller** [comment]
Appears for a couple of seconds 

![mar-27-2017 10-26-38](https://cloud.githubusercontent.com/assets/16238581/24349757/ea4830ba-12d7-11e7-8a31-b8bf754455ce.gif)

**Comment by Jamchiller** [comment]
Top and bottom

**Comment by oliverjam** [comment]
Wtf is that. Nothing to do with the browser so it must be in the video. I can't see it when I play the file in Quicktime though. Looks like some kind of mobile sharing menu with a share/edit/delete option.

What phone was it recorded on? I can probably strip the last half second off to get rid of it.

**Comment by Jamchiller** [comment]
Haha yeah so weird. It looks like it's in the first second, not the last second? But yeah, strip it out if you can

**Comment by oliverjam** [comment]
Better?

**Comment by Jamchiller** [comment]
Fixed! Nice! 

... Hate to bring up more issues, but it seems the iphone is initially loading in the first section - see this gif. For a split second every time I reload the page, the iphone appears and then is pushed down. Is this fixable? 

![mar-28-2017 10-11-07](https://cloud.githubusercontent.com/assets/16238581/24397703/0039eaae-139f-11e7-8ea8-fd153aa6b29c.gif)

**Comment by oliverjam** [comment]
I think it's because images are loaded asynchronously, which means the box containing it has 0 height. Because the iPhone is positioned absolutely to the bottom of that box it sticks up above until the image loads. I can give the box a `min-height` so it doesn't collapse like that.

**Comment by Jamchiller** [comment]
Awesome. It peeks over the browser for a second, it's kinda cute

**Comment by oliverjam** [comment]
I think it's fixed now

**Comment by Jamchiller** [comment]
Looks fixed to me! Whoop. Close this one
