### ISSUE TITLE
Change fonts to Lato

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/workstream-website#30]
Okay I decided. Change to Lato sooooon

**Comment by oliverjam** [comment]
Done. I think Avenir actually looks better though :/ I left both in the code, so you can go into dev tools and click the line with Lato on and off to compare in the page.

![screen shot 2017-03-24 at 22 19 41](https://cloud.githubusercontent.com/assets/9408641/24315632/019c79d2-10e0-11e7-89bb-e2f687bb48d9.png)

**Comment by Jamchiller** [comment]
I agree Avenir looks better. But let's close this
