### ISSUE TITLE
Hand pointer over four screenshots

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/workstream-website#31]
There needs to be some sort of feedback on the four screenshots that tells the user that they're clickable. Hand pointer is an easy solution, otherwise maybe they can highlight on hover? Your call, whicever is easiest

**Comment by oliverjam** [comment]
To avoid getting into a whole pointer debate again I'll say do both.

**Comment by Jamchiller** [comment]
Haha yeah I did think that but yeah let's get this done and then debate pointers for our next website :)

**Comment by oliverjam** [comment]
Done

**Comment by Jamchiller** [comment]
B.e.a.utiful
