### ISSUE TITLE
Put macbook or imac next to iphone

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/workstream-website#32]
As discussed - like this:

![7ab888ec-0f28-11e7-8e07-f16a93ed79cf](https://cloud.githubusercontent.com/assets/16238581/24360186/7f43d842-12fe-11e7-9257-89e9baa119ad.png)

Only if possible

**Comment by oliverjam** [comment]
Turned out to not be too complicated. Keep them in scale is frustrating as the screen shrinks, so the iPhone is a little big at tablet-ish sizes, but I think looks good on desktop and mobile.

**Comment by Jamchiller** [comment]
This actually looks/works really well. Nice!
