### ISSUE TITLE
Pointer cursor for form send button

### ISSUE THREAD

**Issue by oliverjam** [oliverjam/workstream-website#33]
Figured it would be weird to have one button on the page without the pointer.

@Jazzalenko this needs a hover style I think. Any preference on what colour etc?

**Comment by Jamchiller** [comment]
Yeah, agreed. Maybe needs to be a slightly lighter shade of blue rather than change colour completely. Subtle and sexy. Make it fade to the new colour for extra sexiness

**Comment by oliverjam** [comment]
👍

**Comment by oliverjam** [comment]
First attempt done. You can't transition gradient backgrounds so I can't make it fade unfortunately.

**Comment by Jamchiller** [comment]
Beautiful. Happy with that
