### ISSUE TITLE
Home background looks weird in Safari

### ISSUE THREAD

**Issue by oliverjam** [oliverjam/workstream-website#34]
Safari seems to handle transparent gradients differently, so the background looks much shitter there. It's all white and stuff. Not sure what the problem is but I can probably get it to work.

**Comment by Jamchiller** [comment]
Yeah, if you want, can you just hide the boxes on the safari site? That could be easiest

**Comment by oliverjam** [comment]
Not sure I can target Safari without some weird JS hacks. I'll look into the issue later — it's probably fixable.

**Comment by Jamchiller** [comment]
Cool, give it a go

**Comment by oliverjam** [comment]
[Found the issue](https://css-tricks.com/thing-know-gradients-transparent-black/) — as always it's Safari being the odd dickhead out. Apparently they may actually be the only browser correctly implementing gradients (but I'd argue the spec is wrong here, as if I use 'transparent' in a gradient I want the colour to fade to transparent, not fade through the opaque version of the colour before hitting transparent).

Anyway I think I can fix it.

**Comment by oliverjam** [comment]
Okay so I fixed the original issue, the bg looks great in Chrome and isn't broken in Safari anymore. BUT in Safari and Firefox there is banding on the gradient for some reason. Can you see it or is it my screen being weird?

**Comment by Jamchiller** [comment]
Hmm yep I'm getting banding too. Wtf. Anything online about this? Surely browsers should be able to disaply gradients?

**Comment by oliverjam** [comment]
I've googled a bit — apparently you're at the mercy of the browser's rendering engine :/

**Comment by Jamchiller** [comment]
MOtherfucker. Oh well

**Comment by Jamchiller** [comment]
You gonna move this across to lick's git tonight so we can go live tomorrow?

**Comment by oliverjam** [comment]
Done: https://lickcreative.github.io/workstream/

Just need to get Sanj to change the IP with the DNS provider

**Comment by Jamchiller** [comment]
Nice so are you gonna keep working through the issues here but making the changes at the lickcreative git? 

Or shall we move issues to the other one?

**Comment by oliverjam** [comment]
I've set it up so when i push changes here they get mirrored to the lick one

**Comment by Jamchiller** [comment]
Nice! That's awesome!

**Comment by Jamchiller** [comment]
You can close this
