### ISSUE TITLE
Resolve footer issues

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/workstream-website#35]
Could you make the text in the footer vertically aligned? It currently looks weirdly placed because of the size of the logo on the other side: 

![screen shot 2017-03-28 at 09 54 02](https://cloud.githubusercontent.com/assets/16238581/24396833/807a18d6-139c-11e7-9b12-8726f1e8f2e6.png)

Also on narrower displays can it be centrally aligned please? As it looks weird on an iphone 6

![screen shot 2017-03-28 at 09 54 49](https://cloud.githubusercontent.com/assets/16238581/24396877/9afce3f0-139c-11e7-9fc0-2602a460402c.png)

**Comment by oliverjam** [comment]
💥
