### ISSUE TITLE
Replace mac image with non-branded image

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/workstream-website#36]
Will make one for you and put it in assets

**Comment by oliverjam** [comment]
Oh shit yeah, Apple logo

**Comment by Jamchiller** [comment]
I didn't mean that but that too! I meant that it's a Game mockup (where did you get it?!?!)

**Comment by oliverjam** [comment]
Oh right lol. I forgot I put that in ages ago — it's from [this](http://codepen.io/oliverjam/pen/mRvreZ) mock up I did on Codepen after you first showed me the designs at McDonald's

**Comment by Jamchiller** [comment]
Haha sick. I thought it looked similar but eerily different. If I send you the mockup do you want to compile in photoshop or do you want me to make the screen including browser etc? 

I've chucked the standard dashboard in Assets if you need it

**Comment by oliverjam** [comment]
Er I think the screenshot generator I used has only Apple branded machines. If you have a blank fake iMac image then maybe you do it? Would be better with a shadow though since the phone won't match.

**Comment by Jamchiller** [comment]
Okay will do

**Comment by oliverjam** [comment]
@Jazzalenko Still need this

**Comment by Jamchiller** [comment]
Yup I know, jsut so busy at work

**Comment by oliverjam** [comment]
Np problem. If you're happy with the Apple logo I can replace the screenshot and just go with that

**Comment by Jamchiller** [comment]
YEs please. And then I'll try get some time to make one tomorrow

**Comment by Jamchiller** [comment]
Okay I've made one, it's sitting in the Assets folder!

**Comment by oliverjam** [comment]
Done
