### ISSUE TITLE
Move all files to lickcreative github

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/workstream-website#37]
Do we still get free hosting with our second repo or will we need to purchase it?

**Comment by oliverjam** [comment]
Err you can have as many as you like but I'm not sure how domains work. Like if I publish a new repo on Github pages it might end up visible at oliverjam.es/new-repo. I'll check if you give me the Lick login

**Comment by Jazzalenko** [comment]
Username: lickcreative
Password: do51aL9!
