### ISSUE TITLE
Footer text is breaking margins on mobile

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/workstream-website#41]
Check out the site on mobile, the footer text is not wrapping and therefore breaking the max width. Probably easily fixable

**Comment by oliverjam** [comment]
Done

**Comment by Jamchiller** [comment]
Actually doesn't seem fixed?

**Comment by oliverjam** [comment]
It won't be live yet, but is fixed on the [staging domain](https://workstreamx.surge.sh)

**Comment by Jamchiller** [comment]
Ah gotcha! TIL the word staging domain
