### ISSUE TITLE
Legacy browser compatibility? 

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/workstream-website#42]
Just a thought - if the site is breaking massively on browsers like Spencer's, is it worth having a fallback text site for older browsers? Is this easily implementable?

**Comment by oliverjam** [comment]
Figured out why it's so broken even on browsers that should be okay — I have an Autoprefixer task that automatically generates older legacy CSS for stuff like flexbox layouts, but I totally forgot that every time I re-generated CSS after saving a file the autoprefixed version would be over-written. So basically I need to manually run that every time before I push new code...

**Comment by oliverjam** [comment]
It's already a lot better in recent-ish browsers.

IE8 though lol...

![win7_ie_8 0](https://cloud.githubusercontent.com/assets/9408641/24527266/498daf32-1599-11e7-9e7c-4304b21f0d88.png)

**Comment by Jamchiller** [comment]
I'd say this is done
