### ISSUE TITLE
Adding call to action in 4 window section 

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/workstream-website#43]
It has come to my attention that it's not obvious enough that you can click the windows and see different text displayed. We need to work in a solution. One is adding text above the four mp4s, saying 'click the windows below to explore the system' 

Other easier one is adding text at the bottom of 'Dashboard' that says: 
<< Click the windows to explore more Workstream X features.

**Comment by oliverjam** [comment]
Technically did this but also hid that section for now...

**Comment by Jamchiller** [comment]
Perfect
