### ISSUE TITLE
Spacing around 4 boxes

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/workstream-website#45]
This seems to have changed recently? Maybe I just didn't notice it before. 
There's now a lot of space around that section for some reason. 

Chrome: 
![screen shot 2017-03-31 at 11 26 13](https://cloud.githubusercontent.com/assets/16238581/24546827/e88cc1fc-1604-11e7-81fa-f63fcff21ec6.png)

Firefox: 

![screen shot 2017-03-31 at 11 26 54](https://cloud.githubusercontent.com/assets/16238581/24546843/f54dd778-1604-11e7-8485-8503de81a094.png)

**Comment by oliverjam** [comment]
Shrink the screen: it's to make sure there's enough space for the longest possible paragraph that might appear in that section.

Hacky but that whole section is tbh

**Comment by Jamchiller** [comment]
Oh so it must be accomodating this: 

![screen shot 2017-03-31 at 11 59 59](https://cloud.githubusercontent.com/assets/16238581/24547801/98e35620-1609-11e7-9adc-3521a2a0500b.png)

Probably should add in another break point for tablet which fixes this but all good for the moment. Not too much of an issue

**Comment by oliverjam** [comment]
Tbh I'm really unhappy about this whole section. It's so so brittle it could break at any time on any device. Can't think of another way to do this design though

**Comment by Jamchiller** [comment]
Yeah well I guess we live with it for the moment! 

I think a (slightly hacky) fix for th aesthetic issue is adding a teensy bit more spacing on the other sections? Especially because, if you look at the firefox version, the phone is super close to the line so looks out of whack. Adding in a bit more spacing might make it look better? Not much
