### ISSUE TITLE
Integrate Formspree with Contact section

### ISSUE THREAD

**Issue by oliverjam** [oliverjam/workstream-website#5]
- [x] Form sends an email to specified address

- [ ] `success.html` loads to show the email was sent

**Comment by Jamchiller** [comment]
Specified address - contact@workstreamx.com

**Comment by oliverjam** [comment]
@Jazzalenko Any preference about the success page? Could just reproduce the home section from the main site with different text

**Comment by oliverjam** [comment]
I tested locally with my own address and it works fine. They've added a captcha!

I put your address on the live site for now cause I assume the Workstream one doesn't exist yet, so not ideal for testing

**Comment by Jamchiller** [comment]
Nice! Okay well the workstream address is set up now so please put it in! contact@workstreamx.com

**Comment by oliverjam** [comment]
Done. Anymore thought about the success page?

**Comment by Jamchiller** [comment]
I would do that
 Something similar to the success page on my site could work

**Comment by Jamchiller** [comment]
You can close this issue - the emails are now coming through. 

We don't need a success page, the formspree success page is good enough.
