### ISSUE TITLE
Fix big that leads to flashing in Chrome

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/workstream-website#8]
When opened on my computer, everything flashes weirdly. Could be the animation or something?

**Comment by oliverjam** [comment]
Can you give me a quick screen-recording?

Also use devtools to turn the animation off (Inspect element on the background, find `<section class="home" id="home">`, then find the `::after` and `::before` elements, then check the animation off in the CSS section). See if the screen still flashes then.

![screen shot 2017-03-18 at 13 26 28](https://cloud.githubusercontent.com/assets/9408641/24072435/abd246fe-0bde-11e7-9ee9-8c02ee08e73d.png)

**Comment by oliverjam** [comment]
I'm not sure how to fix this. I'll try a few things but browsers don't cope well with big layered animations, especially with rotating gradients. Mine gets those gradient dithering lines across the rectangles as they animate :/

**Comment by Jamchiller** [comment]
Yeah well we can see. Definitely a super sick effect so sad to lose it but may need to tunr off for the time being. There's gotta be a solution as many site have that sorta thing. Maybe they do it differently

**Comment by Jamchiller** [comment]
I think we just need to remove the moving boxes for now as they seem to creating the issue. Can you disable the movement (keep the boxes) and see if this fixes it?

**Comment by oliverjam** [comment]
I can indeed. Will sort later
