### ISSUE TITLE
Fix home page stretching issue

### ISSUE THREAD

**Issue by Jamchiller** [oliverjam/workstream-website#9]
When opened and window isn't a certain length, the X does not resize and takes up the whole screen. 
![screen shot 2017-03-18 at 1 08 04 pm](https://cloud.githubusercontent.com/assets/16238581/24072238/f41b4710-0bdb-11e7-8799-7a179832e4f0.png)

**Comment by oliverjam** [comment]
Yeah that's a combination of the X being too big and the window cutting the text off the bottom. That'll always happen as windows get shorter though.

If you want the X to scale when the window shrinks vertically as well as horizontally then I'll have to do some magic with the `vmin` measurement. It works by calculating the shorter side of the browser (so `30vmin` will be 30% of whichever is shorter, the window width or height). That way it'll always be roughly proportional.

**Comment by Jamchiller** [comment]
Yeah. At this length of window, I feel that both the X and text should bit onto the page. So yeah some vmin magic would be good. Or just make the x a lot smaller and sit in the middle so when the window is longer then there's just more blue space at the top and bottom rather than filling the screen
